services:
  app1:
    build:
      context: .
    environment:
      - APP_NAME=app1
    ports:
      - "5001:5000"
    networks:
      - my-network

  app2:
    build:
      context: .
    environment:
      - APP_NAME=app2
    ports:
      - "5002:5000"
    networks:
      - my-network

  app3:
    build:
      context: .
    environment:
      - APP_NAME=app3
    ports:
      - "5003:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge